language: node_js
env:
  global:
  - secure: njNNm7Yg2Q/X2gJ5f58SklW6HKi1cP4NsLGyiaXXSsGIIPREFvWEdvpNcE+vHMpAyHFJbldQquo+4ztWHlO5pg+Et62zmQr11qsAXhELzs1axmHckHL6R8Q9Fhs9Z9uVVJncJ7qwvrxqoE9eRzCdqnGAgGRlQj19x4hCAb5gkEdlLse0OjqfUYgeWOVbBNjWBwvilMMIvXwUc8y8Oi0gpYN3/63YAm+uFR9RC2JJ6S1gdqs7h7X59mRAhoNV4TRtw7PP4k+jMrpU5VzcsCOW/4C/tEtrSQfjfYjDWM8kHJ379SjSRPQOkExMRewfmWytXZJOtPdxFpnEiO7TPvEOzUW+nIVqEkl4VZZXSnVEKMiHxtW3fXGq8mC2IB7C2lPEPrjDaaUfZiNs5XO7O0lnj+Pb0ShEEpoBrFgg4MEBpace53vRoyp7eAtEIhFlv+9RBLBMfXfImgWyMzW/m85mHBogwt9oToYSgS3IYY7RYo1+eKvm6zb6R5hq2MzgTZvcyPkymry928wkwJmGYI4lZ/zh0++P6pdIchgIFBPK4z/oSlmB51RZd7bPM4qUBcpOk0HhjeHO1Malp5eT3Lbhqg9iM7kVRMLWpsZMQdbCQUcT8bd0cyM6iDmlElQAz14WIKIE8B3pHpJaYocJ6pjNZOJp79XljMKkx2OLSjJIYXg=
  - secure: O3BDvq+A6F7n/Su2cDjOyo9sG+4HlQy/HTKpMK99TosKJMuDHH5xoNQWxdxBDEwURER3EdmA7XCp9la6dHFHZ5NhDMVGboL2ybrFMDuxm5+02+ysWJNuU9lh6SqH06NpaRHtBBlwGAl4f9ExgMk+dRy66JbAcp3HpWn9wNpIXNOwogtdGJwjkiQ9D7qpZ4/UIxIoacFwNafGN0EndkNirA2WLvRt/+uEPOb1ICxbUJ/wi/wFofNkA0LZy89pqIYv53w2iqm+bZBswxDkAPeqzXAed94yupgvYyz/367x3MYRizs4Y6kVh46ALPOeniXN5xk1YXCVWEAu4xZ3sAdKa7Kw2lRVfRN5gsYbLw9y2Fbr3BUhccK/SPT2KhTJWQ8zUyFur+j2Z1eUvi6Z9/hjbZ4PbmvEIrXhXvhv+hLmH7XaYGEwHqA8nb5l/6wAVrAFe/DDclEmGnjOo9HKkC1F8QLTuHAGuqDb0wRqoHZhe92+jmLmW8dD1iloMfjOqkOHDEUufxsKMtK5XD8u6YiHeVHjoZoCM1thd4cu1QFQk7iUpWwoNcxjTmNxRhiIv+9LTppDQvuw0C5TjAlUC+zVizVOIq/FKDsd+GfpZuPt1fZJLWuq1N/wL+dY5fGoO65CfiHs8dq2g2jmq6u8AXz+805udYQNJWMNsCIOHgoidqQ=
cache:
  directories:
  - "~/.npm"
notifications:
  email: false
node_js:
- stable
os:
- linux
script:
- npm run test
after_success:
- npm run semantic-release
branches:
  except:
  - "/^v\\d+\\.\\d+\\.\\d+$/"
